routes/admin.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'AdminDashboardController@index');
Route::get('dashboard', 'AdminDashboardController@index')->name('dashboard');
Route::get('system/cache', 'ApplicationSettingsController@cacheClear')->name('system.cache');
Route::get('system/status', 'ApplicationSettingsController@systemStatus')->name('systeminfo');

// Users
Route::get('users/administrator', 'UserController@administrator')->name('users.administrator');
Route::get('users/list/{state?}', 'UserController@index')->name('users');
Route::get('users/user/{id}/{type}', 'UserController@showUserDetails')->name('users.details');
Route::get('users/user/refers', 'UserController@getReferralTree')->name('users.user.refers');
Route::get('users/export/all', 'UserController@exportUsers')->name('users.export');

Route::post('users/new', 'UserController@saveUser')->name('users.save');
Route::post('users/update', 'UserController@updateAction')->name('users.action');
Route::post('users/update/bulk', 'UserController@bulkAction')->name('users.action.bulk');
Route::post('users/send-email', 'UserController@sendEmail')->name('users.send.email');

// Transactions
Route::get('deposit/{status}', 'TransactionController@allDeposit')->name('transactions.deposit.all');
Route::get('withdraw/{status}', 'TransactionController@allWithdraw')->name('transactions.withdraw.all');
Route::get('referral/{status}', 'TransactionController@allReferral')->name('transactions.referral.all');

Route::get('transactions/list/{list_type?}', 'TransactionController@index')->name('transactions.list');
Route::get('transactions/view', 'TransactionController@showDetails')->name('transaction.details');

Route::post('transactions/update/{action?}', 'TransactionController@actionUpdate')->name('transaction.update');
Route::post('transactions/check/online', 'TransactionController@checkStatus')->name('transaction.status.check');

Route::get('transactions/manual', 'TransactionController@manualTnxAdd')->name('transaction.manual.add');
Route::post('transactions/manual/{type?}', 'TransactionController@manualTnxSave')->name('transaction.manual.save');

// Settings
Route::get('setup', 'QuickSettingsController@index')->name('quick-setup');
Route::any('setup/system', 'QuickSettingsController@quickRegister')->name('quick.register');
Route::post('setup/update', 'QuickSettingsController@updateSettings')->name('quick-setup.save');

Route::get('system/updater', 'UpdateManagerController@index')->name('update.systems');
Route::post('system/updater/install', 'UpdateManagerController@install')->name('update.install');

Route::get('settings/global/general', 'ApplicationSettingsController@general')->name('settings.global.general');
Route::get('settings/global/currencies', 'ApplicationSettingsController@currency')->name('settings.global.currency');
Route::get('settings/global/rewards', 'ApplicationSettingsController@rewards')->name('settings.global.rewards');
Route::get('settings/global/referral', 'ApplicationSettingsController@referrals')->name('settings.global.referral');
Route::get('settings/global/api', 'ApplicationSettingsController@api')->name('settings.global.api');
Route::get('settings/website', 'ApplicationSettingsController@website')->name('settings.website');
Route::get('settings/website/userpanel', 'ApplicationSettingsController@userpanel')->name('settings.website.userpanel');
Route::get('settings/website/appearance', 'ApplicationSettingsController@appearance')->name('settings.website.appearance');
Route::get('settings/website/misc', 'ApplicationSettingsController@misc')->name('settings.website.misc');
Route::get('settings/email', 'ApplicationSettingsController@email')->name('settings.email');
Route::post('settings/email/mailer', 'ApplicationSettingsController@sendTestEmail')->name('settings.email.test');
Route::get('settings/component/system', 'ApplicationSettingsController@componentSystem')->name('settings.component.system');

Route::post('settings/update', 'ApplicationSettingsController@saveSettings')->name('save.app.settings');
Route::post('settings/branding/upload', 'ApplicationSettingsController@storeBranding')->name('save.website.brands');

//Payment
Route::get('settings/gateway/deposit-withdraw', 'ApplicationSettingsController@paymentOptions')->name('settings.gateway.option');
Route::get('settings/gateway/payment-method', 'ApplicationSettingsController@paymentMethods')->name('settings.gateway.payment.list');
Route::get('settings/gateway/withdraw-method', 'ApplicationSettingsController@withdrawMethods')->name('settings.gateway.withdraw.list');

Route::post('settings/gateway/quick-update', 'ApplicationSettingsController@updateMethodActivation')->name('settings.gateway.quick');

// Investment App
Route::get('settings/investment/app', 'ApplicationSettingsController@investmentApp')->name('settings.investment.app');
Route::get('settings/investment/account', 'ApplicationSettingsController@investmentAccount')->name('settings.investment.account');

// Manage Pages
Route::get('manage/pages', 'ManagePagesController@index')->name('manage.pages');
Route::get('manage/pages/create', 'ManagePagesController@create')->name('manage.pages.create');
Route::get('manage/pages/{id}/edit', 'ManagePagesController@edit')->name('manage.pages.edit');

Route::post('manage/pages', 'ManagePagesController@save')->name('manage.pages.save');
Route::post('manage/pages/validate/slug', 'ManagePagesController@validatePageSlug')->name('manage.pages.validate.slug');
Route::post('manage/pages/delete/{id?}', 'ManagePagesController@deletePage')->name('manage.pages.delete');

// Manage Email
Route::get('manage/emails', 'ManageEmailTemplatesController@index')->name('manage.email.template');
Route::get('manage/emails/{slug}', 'ManageEmailTemplatesController@edit')->name('manage.email.template.edit');

Route::post('manage/emails', 'ManageEmailTemplatesController@save')->name('manage.email.template.save');
Route::post('manage/emails/mailer', 'ManageEmailTemplatesController@sendTestEmail')->name('manage.email.template.test');

// System Language
Route::get('/system/languages', 'LanguageController@index')->name('system.langs');
Route::get('/system/languages/{action}', 'LanguageController@actions')->name('system.langs.action');

Route::post('/system/language/create', 'LanguageController@createLang')->name('system.langs.add');
Route::post('/system/language/update/{id?}', 'LanguageController@updateLang')->name('system.langs.update');
Route::post('/system/language/delete/{id?}', 'LanguageController@deleteLang')->name('system.langs.delete');
Route::post('/system/language/process/{action}', 'LanguageController@processLang')->name('system.langs.process.action');

// Profile
Route::get('profile/{type?}', 'ProfileController@show')->name('profile.view');
Route::get('profile/settings/change-email/verify', 'ProfileController@verifyChangeEmail')->name('profile.settings.change.email.verify');
Route::post('profile/activity/clear', 'ProfileController@clearActivity')->name('profile.activity.clear');
Route::post('profile/activity/{id}', 'ProfileController@deleteActivity')->name('profile.activity.delete');

Route::post('profile/update', 'ProfileController@updatePreference')->name('profile.update');
Route::post('profile/update/personal', 'ProfileController@updatePersonalInfo')->name('profile.update.personal');
Route::post('profile/update/address', 'ProfileController@updateAddressInfo')->name('profile.update.address');

Route::post('profile/settings', 'ProfileController@saveSettings')->name('profile.settings.save');
Route::post('profile/settings/change-email', 'ProfileController@changeEmail')->name('profile.settings.change.email');
Route::post('profile/settings/change-email/resend-verify', 'ProfileController@resendVerification')->name('profile.settings.change.email.resend');
Route::post('profile/settings/change-email/cancel-request', 'ProfileController@cancelRequest')->name('profile.settings.change.email.cancel');
Route::post('profile/settings/change-password', 'ProfileController@updatePassword')->name('profile.settings.change.password');
Route::post('profile/settings/2fa/{state}', 'ProfileController@google2fa')->name('profile.settings.2fa');
Route::post('profile/preference', 'ProfileController@preference')->name('profile.preference');

routes/user.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| User Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register user related web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "user" middleware group. Now create something great!
|
*/

Route::get('dashboard', 'UserDashboardController@index')->name('dashboard');
Route::get('profile', 'ProfileController@view')->name('account.profile');
Route::get('profile/accounts', 'WithdrawAccountController@view')->name('account.withdraw-accounts');
Route::get('profile/settings', 'SettingsController@view')->name('account.settings');

Route::get('profile/activity', 'ActivityController@view')->name('account.activity');
Route::get('profile/activity/clear', 'ActivityController@clearActivity')->name('account.activity.clear');
Route::get('profile/activity/{id}', 'ActivityController@destroy')->name('account.activity.delete');

Route::post('profile/personal', 'ProfileController@savePersonalInfo')->name('account.profile.personal');
Route::post('profile/address', 'ProfileController@saveAddressInfo')->name('account.profile.address');
Route::post('profile/change-unverified-email', 'ProfileController@updateUnverifiedEmail')->name('account.profile.update-unverified-email');
Route::post('profile/verify-unverified-email/{user}', 'ProfileController@verifyUnverifiedEmail')->name('account.profile.verify-unverified-email');

Route::post('profile/preference', 'SettingsController@preference')->name('account.preference');
Route::post('profile/settings', 'SettingsController@saveSettings')->name('account.settings.save');
Route::post('profile/settings/email', 'SettingsController@changeEmail')->name('account.settings.change.email');
Route::post('profile/settings/email/resend', 'SettingsController@resendVerification')->name('account.settings.change.email.resend');
Route::post('profile/settings/email/cancel', 'SettingsController@cancelRequest')->name('account.settings.change.email.cancel');
Route::post('profile/settings/password', 'SettingsController@changePassword')->name('account.settings.change.password');
Route::post('profile/settings/password/new', 'SettingsController@addPassword')->name('account.settings.add.password');
Route::post('profile/settings/2fa/{state}', 'SettingsController@google2fa')->name('account.settings.2fa');
Route::post('profile/settings/social/{platform}/{action}', 'SettingsController@social')->name('account.settings.social');
Route::post('update/setting', 'SettingsController@updateUserSettings')->name('update.setting');

Route::get('deposit', 'TransactionController@depositPaymentMethod')->name('deposit');
Route::get('deposit/online/{status}/{tnx?}', 'TransactionController@onlineDepositComplete')->name('deposit.complete.online');
Route::get('deposit/{status}/{tnx?}', 'TransactionController@depositComplete')->name('deposit.complete');
Route::post('deposit/amount', 'TransactionController@depositAmount')->name('deposit.amount.form');
Route::post('deposit/preview', 'TransactionController@depositPreview')->name('deposit.preview.form');
Route::post('deposit/confirm', 'TransactionController@depositConfirm')->name('deposit.confirm');

Route::get('withdraw', 'TransactionController@showWithdrawMethod')->name('withdraw');
Route::get('withdraw/redirect/amount', 'TransactionController@withdrawAmount')->name('withdraw.redirect.amount');
Route::post('withdraw/amount', 'TransactionController@withdrawAmount')->name('withdraw.amount.form');
Route::post('withdraw/preview', 'TransactionController@withdrawPreview')->name('withdraw.preview.form');
Route::post('withdraw/confirm', 'TransactionController@withdrawConfirm')->name('withdraw.confirm');

Route::get('transactions', 'TransactionController@list')->name('transaction.list');
Route::get('transactions/details', 'TransactionController@viewTransactionDetails')->name('transaction.details');
Route::get('transaction/{status}/{tnx?}', 'TransactionController@actionTransactionStatus')->name('transaction.action');

Route::get('referrals', 'ReferralController@index')->name('referrals');

// Welcome setup
Route::get('welcome', 'ProfileController@welcome')->name('account.welcome');
Route::get('congratulation', 'ProfileController@congrats')->name('account.congrats');

Route::post('profile/complete', 'ProfileController@completeProfile')->name('account.profile.complete');
Route::post('validate/username', 'ProfileController@validateUsername')->name('validate.username');

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'PublicController@welcome')->name('welcome');
Route::get('/language', 'PublicController@language')->name('language');
Route::get('/investments', 'PublicController@investments')->name('investments');
Route::get('/page/{slug}', 'PageController')->name('show.page');
Route::post('/policy-consent', 'PublicController@gdprCookie')->name('gdpr.cookie');

Route::middleware(['guest'])->group(function(){

	Route::get('/login', 'AuthController@loginForm')->name('auth.login.form');
	Route::post('/login', 'AuthController@login')->name('auth.login');
	Route::post('/auth/social/confirm', 'AuthController@confirmSocialAuth')->name('auth.social.confirm');
	Route::get('/auth/social/confirm', 'AuthController@confirmSocialView')->name('auth.social.confirm.signup');
	Route::get('/auth/social/verify','AuthController@authSocialVerify')->name('auth.social.verify');
	Route::get('/auth/social/{type}','AuthController@socialAuth')->name('auth.social');
	Route::get('/auth/2fa','AuthController@authVerifyForm')->name('auth.2fa.form');
	Route::post('/auth/2fa','AuthController@authVerify2FA')->name('auth.2fa');

	Route::get('/register', 'AuthController@registerForm')->name('auth.register.form');
	Route::post('/register', 'AuthController@register')->name('auth.register');

	Route::get('/password/forget', 'AuthController@forgetPasswordView')->name('auth.forget.form');
	Route::post('/password/forget', 'AuthController@forgetPassword')->name('auth.forget');

});
Route::get('/auth/social/{type}/callback', 'AuthController@socialCallback')->name('auth.social.callback');
Route::get('/password/reset', 'AuthController@resetPasswordView')->name('auth.reset.page');
Route::post('/password/reset', 'AuthController@resetPassword')->name('auth.reset');


Route::get('/email/confirm', 'AuthController@confirm')->name('auth.confirm');
Route::get('/verify', 'AuthController@verifyEmail')->name('auth.email.verify');
Route::get('/verify/email', 'AuthController@verifyEmailUpdate')->name('auth.email.update.verify');

Route::get('/account/verify','AuthController@accountVerification')->name('auth.email.verification');
Route::post('/email/resend','AuthController@resendVerifyEmail')->name('auth.email.resend');
Route::post('/email/change','AuthController@updateEmailAndVerify')->name('auth.email.change');
Route::post('/submit-form', 'ContactController@contact')->name('contact.form');

Route::post('logout', 'AuthController@logout')->middleware('auth')->name('auth.logout');
Route::get('invite', 'AuthController@referral')->name('auth.invite');

// Route while maintaince enable
Route::get('maintenance', 'MaintenanceController@index')->name('maintenance');
Route::get('/admin/login', 'AuthController@loginForm')->name('admin.login');

app/Models/UserActivity.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class UserActivity extends Model
{
    /**
     * @var bool
     */
    public $timestamps = false;

    /**
     * @var string[]
     */
    protected $fillable = [
        'user_id',
        'session',
        'ip',
        'meta',
        'browser',
        'device',
        'platform',
        'version',
    ];

    /**
     * @var string[]
     */
    protected $casts = [
        'version' => 'array',
        'session' => 'datetime'
    ];

    /**
     * @return string
     * @version 1.0.0
     * @since 1.0
     */
    public function getBrowserWithPlatformAttribute()
    {
        return "{$this->browser} on {$this->platform}";
    }
}

resources/views/admin/user/activities.blade.php
@section('title', __("Login Activities"))

<div class="nk-block-head">
    <h5 class="title">{{ __('Login Activities') }}</h5>
    <p>{{ __('The activities of login for the user.') }}</p>
</div>
<div class="nk-block is-stretch">
    <table class="table table-ulogs">
        <thead>
        <tr>
            <th class="tb-col-os"><span class="overline-title">{{ __('Browser') }} <span class="d-sm-none">/ {{ __('IP') }}</span></span></th>
            <th class="tb-col-ip"><span class="overline-title">{{ __('IP') }}</span></th>
            <th class="tb-col-time"><span class="overline-title">{{ __('Time') }}</span></th>
        </tr>
        </thead>
        <tbody>
        @forelse($user->activities as $activity)
            <tr>
                <td class="tb-col-os">{{ $activity->browser_with_platform }}</td>
                <td class="tb-col-ip"><span class="sub-text">{{ $activity->ip }}</span></td>
                <td class="tb-col-time">
                    <span class="sub-text">{{ show_date($activity->session) }}  <span class="d-none d-sm-inline-block">{{ show_time($activity->session) }}</span></span>
                </td>
            </tr>
        @empty
            <tr>
                <td class="text-center pt-4" colspan="3">{{ __("No activity log found!") }}</td>
            </tr>
        @endforelse
        </tbody>
    </table>
</div>
@if($user->meta('last_clear_activity'))
<div class="notes mt-3 font-italic text-soft small">
    <p>{{  __('Last cleared log at :date', ['date' => show_date($user->meta('last_clear_activity'), true) ]) }}</p>
</div>
@endif

resources/views/admin/user/investments.blade.php
@php 
use \App\Enums\TransactionType as TType;
use \App\Enums\TransactionCalcType as TCType;

$base_currency = base_currency();

$investments = data_get($user,'allInvested');
$statements = data_get($user,'ivStatements');
@endphp

@section('title', __("Investments"))

<div class="nk-block-head">
    <div class="nk-block-between g-3">
        <div class="nk-block-head-content">
            <h5 class="title">{{ __('Invested Plans') }}</h5>
            <p>{{ __('Recent :num invested plans made by user.',['num' => 10]) }}</p>
        </div>
        <div class="nk-block-head-content">
            <a href="{{ route('admin.investment.list',['user' => the_uid($user->id)]) }}">{{ __('View All') }}</a>
        </div>
    </div>
</div>

<div class="nk-block is-stretch">
    <div class="nk-tb-list nk-tb-ivx{{ user_meta('iv_invest_display') == 'compact' ? ' is-compact': '' }}">
        <div class="nk-tb-item nk-tb-head">
            <div class="nk-tb-col"><span>{{ __('Plan') }}</span></div>
            <div class="nk-tb-col tb-col-lg"><span>{{ __('Start Date') }}</span></div>
            <div class="nk-tb-col tb-col-lg"><span>{{ __('End Date') }}</span></div>
            <div class="nk-tb-col tb-col-lg"><span>{{ __('Investment ID') }}</span></div>
            <div class="nk-tb-col"><span>{{ __('Amount') }}</span></div>
            <div class="nk-tb-col tb-col-sm"><span>{{ __('Status') }}</span></div>
            <div class="nk-tb-col"><span>&nbsp;</span></div>
        </div>

        @forelse($investments as $plan)
            <div class="nk-tb-item">
                <div class="nk-tb-col">
                    <div class="align-center">
                        <div class="user-avatar user-avatar-sm bg-light">
                            <span>{{ strtoupper(substr(data_get($plan, 'scheme.short'), 0, 2)) }}</span>
                        </div>
                        <span class="tb-sub ml-2">{{ data_get($plan, 'scheme.name') }} <span class="d-none d-md-inline">- {{ data_get($plan, 'calc_details_alter') }}</span></span>
                    </div>
                </div>
                <div class="nk-tb-col tb-col-lg">
                    <span class="tb-sub">{{ show_date(data_get($plan, 'term_start'), true) }}</span>
                </div>
                <div class="nk-tb-col tb-col-lg">
                    <span class="tb-sub">{{ show_date(data_get($plan, 'term_end'), true) }}</span>
                </div>
                <div class="nk-tb-col tb-col-lg">
                    <span class="tb-sub">{{ data_get($plan, 'ivx') }}</span>
                </div>
                <div class="nk-tb-col">
                    <span class="tb-sub tb-amount">{{ money(data_get($plan, 'amount'), base_currency()) }}</span>
                </div>
                <div class="nk-tb-col tb-col-sm">
                    @if(data_get($plan, 'status')=='active')
                    <div class="progress progress-sm w-100px nk-tooltip" title="{{ __("Received :amount (:percent)", ['amount' => money(data_get($plan, 'received', 0), base_currency()), 'percent' => data_get($plan, 'progress', 0).'%']) }}">
                        <div class="progress-bar" data-progress="{{ data_get($plan, 'progress', 0) }}"></div>
                    </div>
                    @else 
                    <span class="badge badge-dim {{ the_state(data_get($plan, 'status'), ['prefix' => 'badge']) }}">{{ __(ucfirst(data_get($plan, 'status'))) }}</span>
                    @endif
                </div>
                <div class="nk-tb-col nk-tb-col-action">
                    <a href="{{ route('admin.investment.details', ['id' => the_hash($plan->id)]) }}" target="_blank" class="text-soft btn btn-sm btn-icon btn-trigger"><em class="icon ni ni-chevron-right"></em></a>
                </div>    
            </div>
        @empty
            <div class="nk-tb-item">
                <div class="nk-tb-col">{{ __('No transactions history found!') }}</div>
            </div>
        @endforelse
    </div>
</div>

<div class="nk-block-head">
    <div class="nk-block-between g-3">
        <div class="nk-block-head-content">
            <h5 class="title">{{ __('Invested Statements') }}</h5>
            <p>{{ __('Recent :num investment transactions.',['num' => 15]) }}</p>
        </div>
        <div class="nk-block-head-content">
            <a href="{{ route('admin.investment.transactions.list',['user' => the_uid($user->id)]) }}">{{ __('View All') }}</a>
        </div>
    </div>
</div>

<div class="nk-block is-stretch is-compact">
    <div class="nk-tb-list nk-tb-ivx{{ user_meta('iv_invest_display') == 'compact' ? ' is-compact': '' }}">
        <div class="nk-tb-item nk-tb-head">
            <div class="nk-tb-col"><span>{{ __('Statement ID') }}</span></div>
            <div class="nk-tb-col tb-col-lg"><span>{{ __('Date & Time') }}</span></div>
            <div class="nk-tb-col tb-col-lg"><span>{{ __('Details') }}</span></div>
            <div class="nk-tb-col tb-col-lg"><span>{{ __('Type') }}</span></div>
            <div class="nk-tb-col text-right"><span>{{ __('Amount') }}</span></div>
        </div>
        @forelse($statements as $statement)
            <div class="nk-tb-item" id="tnx-row-{{ $statement->id }}">
                @include('investment.admin.statement.transaction-row', ['transaction' => $statement, 'hide_user'=>true])
            </div>
        @empty
            <div class="nk-tb-item">
                <div class="nk-tb-col">{{ __('No transactions history found!') }}</div>
            </div>
        @endforelse
    </div>
</div>

resources/views/admin/user/pagination.blade.php
@if ($paginator->hasPages())
    <div class="g">
        <ul class="pagination justify-content-center justify-content-md-start">
            @if($paginator->onFirstPage())
                <li class="page-item"><a class="page-link disabled"
                                         href="javascript:void(0)">{{ __('Prev') }}</a></li>
            @else
                <li class="page-item"><a class="page-link"
                                         href="{{ $paginator->previousPageUrl() }}">{{ __('Prev') }}</a></li>
            @endif

            @foreach ($elements as $element)
                @if (is_string($element))
                    <li class="page-item"><span class="page-link"><em class="icon ni ni-more-h"></em></span></li>
                @endif

                @if (is_array($element))
                    @foreach ($element as $page => $url)
                        @if ($page == $paginator->currentPage())
                            <li class="page-item active"><a class="page-link" href="javascript:void(0)">{{ $page }}</a>
                            </li>
                        @else
                            <li class="page-item"><a class="page-link" href="{{$url}}">{{ $page }}</a></li>
                        @endif
                    @endforeach
                @endif
            @endforeach

            @if ($paginator->hasMorePages())
                <li class="page-item"><a class="page-link" href="{{ $paginator->nextPageUrl() }}">{{ __('Next') }}</a>
                </li>
            @else
                <li class="page-item"><a class="page-link disabled" href="javascript:void(0)">{{ __('Next') }}</a></li>
            @endif
        </ul>
    </div>
    <div class="g">
        <div class="pagination-goto d-flex justify-content-center justify-content-md-start gx-3">
            <div>{{ __('Page') }}</div>
            <div>
                <select class="form-select form-select-sm pagination-dropdown" data-search="on" data-dropdown="xs center">
                    @for($i = 1; $i <= $paginator->lastPage(); $i++ )
                        <option value="{{ $paginator->url($i) }}" @if($i == $paginator->currentPage()) selected @endif>{{ $i }}</option>
                    @endfor
                </select>
            </div>
            <div>{{ __('OF') }} {{ $paginator->lastPage() }}</div>
        </div>
    </div>
@endif

resources/views/admin/user/referrals.blade.php
@section('title', __("Referral Activities"))

<div class="nk-block-head">
    <h5 class="title">{{ __('Referral Activities') }}</h5>
    <p>{{ __('The referral members tree view of this user.') }}</p>
</div>
<div class="nk-block is-stretch">
    <div class="nk-tree-cointainer" data-simplebar>
        <div class="nk-tree sm">
            <ul class="nk-tree-pr">
                <li class="nk-tree-cl">
                    @include('admin.user.referral-tree.user-info', ['user' => $user, 'treeCollapse' => false, 'first' => true])
                    @if(count(data_get($user, 'referrals', [])) > 0)
                        <ul class="nk-tree-pr">
                            @foreach(data_get($user, 'referrals', []) as $referral)
                                <li class="nk-tree-cl" id="tree-id-{{ data_get($referral, 'referred.id') }}">
                                    @include('admin.user.referral-tree.user-info', ['user' => data_get($referral, 'referred')])
                                </li>
                            @endforeach
                        </ul>
                    @endif
                </li>
            </ul>
        </div>
    </div>
</div>

@push('scripts')
<script>
    !(function (App, $) {
        $(document).ready(function(){
            $(document).on('click', '.tree-collapse', function(){
                let elm = $(this);
                let plusIcon = elm.children('.ni-plus-circle-fill');
                let loader = elm.children('.spinner-border');
                if (elm.hasClass('is-clicked')) {
                    return;
                }

                elm.addClass('is-clicked');

                let id = $(this).data('user_id');
                let treeContainer = $('#tree-id-'+id);
                if (treeContainer.children(".nk-tree-pr").length === 0) {
                    plusIcon.addClass('d-none');
                    loader.removeClass('d-none');
                    let url = '{{ route('admin.users.user.refers') }}';
                    App.Form.toAjax(url, {"id": id}, {
                        "method": "GET",
                        "onSuccess": function (res) {
                            treeContainer.append(res);
                            App.Treetip('.uinfo-pop');
                            elm.removeClass('is-clicked');
                            loader.addClass('d-none');
                            plusIcon.removeClass('d-none');
                            plusIcon.removeClass('ni-plus-circle-fill');
                            plusIcon.addClass('ni-plus');
                        }
                    });
                }
            });
        });
    })(NioApp, jQuery);
</script>
@endpush